### ISSUE TITLE
预训练过程

### ISSUE THREAD

**Issue by LemonQC** [Zhiquan-Wen/TDS#2]
您好，您能提供一下预训练UpDn的过程么，是自己划分了一部分数据验证来保存模型还是在整个训练集上验证；另外，您提供的预训练模型连接无法访问，谢谢

**Comment by Zhiquan-Wen** [comment]
我们这的预训练UpDn其实就是使用Binary Cross entropy 作为loss，在VQACP2 训练集上训练，在VQACP2 测试集上测试，选择准确率最高的模型。没有特殊的操作。

然后预训练模型无法访问的话，可能需要开代理，或者你在Released tags里边找到对应的模型然后选择不同的下载渠道下载下来

**Comment by LemonQC** [comment]
好的，问题已经解决，可以训练，复现了结果
