### ISSUE TITLE
vilbert代码更新

### ISSUE THREAD

**Issue by LemonQC** [Zhiquan-Wen/TDS#4]
您好，大约什么时候能更新vilbert代码呢，目前另外两个都已经正常复现了

**Comment by Zhiquan-Wen** [comment]
vilbert 无法复现吗？我这跑结果是正常的

**Comment by LemonQC** [comment]
好像git上没有代码呀。

**Comment by Zhiquan-Wen** [comment]
已更新

**Comment by LemonQC** [comment]
好像参数文件有错误，涉及模型的参数都没有
![image](https://github.com/Zhiquan-Wen/TDS/assets/30914380/ddf77f01-33de-4a7d-93bf-dcb867531a11)

**Comment by LemonQC** [comment]
另外缺少一些文件，比如
![image](https://github.com/Zhiquan-Wen/TDS/assets/30914380/eab9f862-e817-4d39-a338-0269fe4b5c07)

**Comment by Zhiquan-Wen** [comment]
已更新，请参考Vilbert的[README_TDS.md](https://github.com/Zhiquan-Wen/TDS/blob/main/vilbert-multi-task/README_TDS.md)

**Comment by LemonQC** [comment]
感谢您的回复，已经可以正常运行，请问vqacpv1是否也可以直接用这个imgid_to_height_and_width.npy

**Comment by Zhiquan-Wen** [comment]
是的，他们图片是通用的

**Comment by LemonQC** [comment]
好的，感谢您的帮助
