### ISSUE TITLE
可否提供一下LXMERT在VQACP-V1上的learning rate？

### ISSUE THREAD

**Issue by LemonQC** [Zhiquan-Wen/TDS#5]
目前复现的结果相比于论文低3个点，在改用lr=0.00002的时候，效果更差
![image](https://github.com/Zhiquan-Wen/TDS/assets/30914380/21aec013-733b-42af-b55d-c9fa76544b1a)

**Comment by Zhiquan-Wen** [comment]
emm，你的learning rate错了吧，我设置的是0.0002，你这个低了一个数量级

**Comment by LemonQC** [comment]
好的，我尝试一下

**Comment by LemonQC** [comment]
基本复现
